language: go
go:
  - "1.2.1"
# command to install dependencies
install:
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_386-1.9.6.zip && unzip -q go_appengine_sdk_linux_386-1.9.6.zip
# command to run tests
# script: python go_appengine/goapp test
script: go_appengine/goapp build