language: go
go:
- 1.2.1
install:
- curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.13.zip
  && unzip -q go_appengine_sdk_linux_amd64-1.9.13.zip
script:
- ./go_appengine/goapp test ./tests;
- ./go_appengine/goapp build ./noughtscrosses;
