language: go
go:
  - "1.2.1"

# Set it up
install:
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.11.zip && unzip -q go_appengine_sdk_linux_amd64-1.9.11.zip

# command to run tests
script: ./go_appengine/goapp build