language: python
python:
  - "2.7"
# command to install dependencies
install:
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_386-1.9.6.zip && unzip -q go_appengine_sdk_linux_386-1.9.6.zip
# command to run tests
script: echo "n" | python go_appengine/dev_appserver.py .