language: python
python:
  - "2.7"
# command to install dependencies
install:
  - curl -O http://googleappengine.googlecode.com/files/google_appengine_1.8.9.zip && unzip -q google_appengine_1.8.9.zip
# command to run tests
script: echo "n" | python google_appengine/dev_appserver.py .