language: go
go:
  - "1.2.1"

# Set it up
install:
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.7.zip && unzip -q go_appengine_sdk_linux_amd64-1.9.7.zip
  - chmod +x ./go_appengine/goroot/bin/goapp
  - export GOROOT=go_appengine/goroot
  - export GOPATH=go_appengine/gopath

# command to run tests
script: ./go_appengine/goroot/bin/goapp build